import { ArtInfo } from '@custom-types/artInfo';

export const ARTWORK_EXAMPLE: ArtInfo = {
  id: '1',
  title: 'Art Title',
  artistTitle: 'Artist Name',
  isPublicDomain: true,
  dateStart: 2020,
  dateEnd: 2023,
  placeOfOrigin: 'Place of Origin',
  dimensions: '10x10',
  creditLine: 'Credit Line',
  imageId: 'image1',
  themeTitles: ['Theme 1', 'Theme 2'],
};

export const ARTWORK_LIST_EXAMPLE: ArtInfo[] = [
  {
    id: '1',
    title: 'Art A',
    artistTitle: 'Artist A',
    isPublicDomain: true,
    dateStart: 2020,
    dateEnd: 2023,
    placeOfOrigin: 'Place A',
    dimensions: '10x10',
    creditLine: 'Credit A',
    imageId: 'image1',
    themeTitles: [],
  },
  {
    id: '2',
    title: 'Art B',
    artistTitle: 'Artist B',
    isPublicDomain: true,
    dateStart: 2019,
    dateEnd: 2020,
    placeOfOrigin: 'Place B',
    dimensions: '10x10',
    creditLine: 'Credit B',
    imageId: 'image2',
    themeTitles: [],
  },
  {
    id: '3',
    title: 'Art C',
    artistTitle: 'Artist C',
    isPublicDomain: true,
    dateStart: 2000,
    dateEnd: 2003,
    placeOfOrigin: 'Place C',
    dimensions: '10x10',
    creditLine: 'Credit C',
    imageId: 'image3',
    themeTitles: [],
  },
];
